import type { Metadata } from "next";
import { LegalPageShell } from "@/components/legal-page-shell";
import { siteConfig } from "@/config/site";
import { languageAlternates } from "@/lib/i18n";

export const metadata: Metadata = {
  title: "Privacyverklaring",
  description: "Hoe MelonCactus omgaat met aanvragen, websiteanalyse en persoonsgegevens in onderzoek uit openbare bronnen.",
  alternates: languageAlternates("/privacy", "nl"),
};

export default function DutchPrivacyPage() {
  return (
    <LegalPageShell locale="nl" title="Privacyverklaring" intro="Hoe wij omgaan met persoonsgegevens wanneer u de website bezoekt, een aanvraag doet of met ons samenwerkt." updated="3 oktober 2026">
      <h2>Wie is verantwoordelijk?</h2>
      <p>{siteConfig.legalName}, een eenmanszaak die MelonCactus exploiteert, is verwerkingsverantwoordelijke voor de website, zakelijke contacten en eigen opdrachtadministratie (KvK-nummer {siteConfig.registrationNumber}; btw-id {siteConfig.vatId}). Bij onderzoek in opdracht bepalen wij onze rol per opdracht. Ons bedrijfsadres is {siteConfig.postalAddress}. Voor vragen of privacyverzoeken mailt u <a href={`mailto:${siteConfig.businessEmail}`}>{siteConfig.businessEmail}</a> of belt u <a href={siteConfig.businessPhoneHref}>{siteConfig.businessPhoneDisplay}</a>.</p>
      <h2>Aanvragen en zakelijke correspondentie</h2>
      <p>Het formulier vraagt uw naam, zakelijke e-mailadres, bedrijf en functie of rol, de beslissing en het onderzoeksobject, en de gewenste termijn. Opdrachtniveau, geografisch gebied, budget, aanvullende context en het verzoek om een geheimhoudingsovereenkomst te bespreken zijn optioneel. Wij gebruiken deze gegevens en verdere zakelijke correspondentie om uw vraag te beoordelen en te beantwoorden, eventueel een voorstel te doen en met u te communiceren. Een aanvraag is nog geen aanvaarde opdracht; een NDA-verzoek vormt nog geen overeenkomst. Stuur in het eerste formulier geen vertrouwelijke documenten, wachtwoorden of andere toegangsgegevens, onrechtmatig verkregen materiaal, bijzondere categorieën persoonsgegevens of meer persoonsgegevens dan nodig is.</p>
      <p>Als u zelf als natuurlijk persoon een overeenkomst aanvraagt of sluit, verwerken wij de daarvoor noodzakelijke gegevens voor stappen op uw verzoek vóór de overeenkomst of voor de uitvoering ervan. Voor medewerkers en andere contactpersonen die namens een bedrijf handelen, gebruiken wij ons gerechtvaardigd belang om zakelijke aanvragen en correspondentie te behandelen. Wij beperken dit tot relevante gegevens, gebruiken het formulier niet voor een marketinginschrijving en respecteren uw recht van bezwaar.</p>
      <h2>Opdrachten en onderzoek in openbare bronnen</h2>
      <p>Bij een overeengekomen opdracht gebruiken wij contact-, project- en factuurgegevens voor uitvoering en administratie. Voor een individuele opdrachtgever kan uitvoering van de overeenkomst de grondslag zijn; voor vertegenwoordigers van een bedrijf gebruiken wij ons gerechtvaardigd belang bij die zakelijke uitvoering. Voor noodzakelijke financiële administratie geldt daarnaast een wettelijke verplichting. Onderzoek kan persoonsgegevens uit rechtmatig toegankelijke openbare bronnen omvatten. Ook openbare gegevens blijven persoonsgegevens. Per opdracht bepalen wij onze rol en beoordelen wij de noodzaak, evenredigheid, professionele relevantie, bronbetrouwbaarheid en informatieplichten voor indirect verkregen gegevens. Afhankelijk van die beoordeling kan ons gerechtvaardigd belang of een andere toepasselijke grondslag gelden. Wij nemen niet aan dat een uitzondering op de informatieplicht automatisch geldt.</p>
      <h2>Hosting, beveiliging en websiteanalyse</h2>
      <p>Vercel verzorgt de hosting en kan technische verzoek- en beveiligingsgegevens verwerken om de website te leveren en te beschermen. Voor een bereikbare en veilige website gebruiken wij ons gerechtvaardigd belang. Met Vercel Web Analytics meten wij uitsluitend paginaweergaven op bekende openbare Engelse en Nederlandse pagina&apos;s, om de navigatie en inhoud van de website te verbeteren. Onze websitecode verwijdert queryparameters en fragmenten uit de pagina-URL die zij als Analytics-gebeurtenis doorstuurt en verstuurt geen formulierwaarden als Analytics-gebeurtenissen. Volgens Vercel kunnen de statistische gegevens onder meer het tijdstip, het paginapad, de verwijzende website, de globale locatie en browser- en apparaatgegevens omvatten. Bij ontvangst van een verzoek kan Vercel ook verbindingsgegevens zoals een IP-adres verwerken; Vercel beschrijft een kortdurende bezoekerhash op basis van het inkomende verzoek, zonder cookies van derden voor Analytics. Wij gebruiken deze meting niet voor advertenties of individuele bezoekersprofielen. Voor deze beperkte meting gebruiken wij ons gerechtvaardigd belang om het gebruik van de website te begrijpen en te verbeteren. U kunt bezwaar maken door te mailen naar <a href={`mailto:${siteConfig.businessEmail}`}>{siteConfig.businessEmail}</a>. Dat een bezoekerssessie na 24 uur vervalt, betekent niet dat alle Analytics- of hostinggegevens dan zijn verwijderd.</p>
      <h2>Ontvangers en verwerking buiten Europa</h2>
      <p>Resend bezorgt formulieraanvragen in onze zakelijke mailbox, die door OVHcloud via Zimbra wordt geleverd; Outlook is de e-mailclient. Vercel verzorgt hosting en websiteanalyse. Onderzoekswerkbestanden en rapporten staan momenteel lokaal op onze computer. Wij delen gegevens met dienstverleners voor zover nodig voor deze doelen en, bij een opdracht, met de opdrachtgever of andere afgesproken ontvangers. Een deel van de verwerking vindt buiten de Europese Economische Ruimte plaats: Resend bewaart bijvoorbeeld e-mailinhoud en afleverlogs in de Verenigde Staten. Wij beloven geen opslag uitsluitend binnen de EER. De <a href="https://resend.com/legal/dpa">gepubliceerde verwerkersovereenkomst van Resend</a> beschrijft wanneer zij bindend wordt en bevat EU-modelcontractbepalingen voor toepasselijke doorgiften; Resend beschrijft ook deelname aan het EU–VS Data Privacy Framework. De <a href="https://vercel.com/legal/dpa">verwerkersovereenkomst voor Vercel Pro</a> neemt EU-modelcontractbepalingen op voor doorgiften waarvoor die nodig zijn. Dit zijn leveranciersspecifieke waarborgen, geen garantie dat alle verwerking in Europa plaatsvindt. U kunt via <a href={`mailto:${siteConfig.businessEmail}`}>{siteConfig.businessEmail}</a> meer informatie vragen over de waarborgen die voor uw gegevens relevant zijn.</p>
      <h2>Hoe lang bewaren wij gegevens?</h2>
      <p>Aanvragen die niet tot een opdracht leiden, inclusief de bijbehorende correspondentie, verwijderen wij uiterlijk twaalf maanden na het laatste inhoudelijke contact uit onze actieve zakelijke mailbox en eigen werkbestanden, of eerder wanneer opvolging niet meer nodig is. Onderzoekswerkbestanden van een uitgevoerde opdracht verwijderen wij uiterlijk 24 maanden na definitieve oplevering uit onze actieve werkbestanden, of eerder wanneer zij niet meer nodig zijn. Definitieve rapporten bewaren wij alleen zolang zij nodig zijn voor correcties of evenredige contractuele aanspraken; wij beoordelen ze afzonderlijk van de werkbestanden. Opdrachtbevestigingen en andere stukken die voor de financiële administratie nodig zijn, bewaren wij gedurende de toepasselijke wettelijke termijn, in Nederland doorgaans zeven jaar. Een concrete juridische aanspraak kan een langere, afzonderlijk beoordeelde bewaring van alleen de betreffende stukken rechtvaardigen. Deze termijnen voor actieve bestanden zijn geen garantie over kopieën of beveiligingsgegevens bij leveranciers. Daarvoor kunnen andere verwijderprocessen, back-upcycli en wettelijke uitzonderingen gelden. Resend beschrijft een reguliere termijn van 30 dagen voor e-mailinhoud en logs bij zijn Free-, Pro- en Scale-abonnementen; de afzonderlijke termijn na accountbeëindiging is niet de bewaartermijn voor onze actieve mailbox. Volgens Vercel vervalt de Analytics-bezoekerssessie na 24 uur; dat is geen algemene verwijdertermijn voor alle Analytics- of hostinggegevens.</p>
      <h2>Uw rechten</h2>
      <p>U kunt verzoeken om inzage, correctie, verwijdering of beperking van de verwerking en bezwaar maken tegen verwerking op grond van gerechtvaardigd belang. Gegevensoverdraagbaarheid geldt waar de wettelijke voorwaarden zijn vervuld. Als wij voor een specifieke verwerking ooit toestemming gebruiken, kunt u die intrekken zonder gevolgen voor eerdere rechtmatige verwerking. Mail ons uw verzoek; wij vragen alleen gegevens die nodig zijn om uw identiteit vast te stellen. U kunt ook een klacht indienen bij de Autoriteit Persoonsgegevens.</p>
      <h2>Wijzigingen</h2>
      <p>Wij passen deze verklaring aan bij wezenlijke veranderingen in onze verwerking en vermelden de wijzigingsdatum hierboven. Waar nodig maken wij belangrijke wijzigingen via een passend kanaal bekend.</p>
    </LegalPageShell>
  );
}
