import type { Metadata } from "next";
import { ButtonLink } from "@/components/buttons";
import { ConfidenceBadge } from "@/components/confidence-badge";
import { Container } from "@/components/container";
import { PageHeader } from "@/components/page-header";
import { SampleEvidenceTable } from "@/components/sample-evidence-table";
import { languageAlternates } from "@/lib/i18n";

export const metadata: Metadata = {
  title: "Representative Sample Report",
  description: "A fictional demonstration of the structure, evidence standards and confidence model used in a MelonCactus report.",
  alternates: languageAlternates("/sample-report", "en"),
};

export default function SampleReportPage() {
  return (
    <article className="sample-report">
      <PageHeader eyebrow="Representative demonstration" title="Production Readiness Assessment" intro="A fictional sample showing how evidence, assessment, confidence and limitations are presented. Northstar Thermal Systems and all source material below are invented for demonstration purposes." breadcrumbs={[{ label: "Sample Report" }]} />
      <section className="report-cover"><Container><div className="report-meta"><div><span>Reference</span><strong>MC-DEMO-001</strong></div><div><span>Status</span><strong>Fictional demonstration</strong></div><div><span>Subject</span><strong>Northstar Thermal Systems</strong></div><div><span>Evidence cut-off</span><strong>Illustrative only</strong></div></div></Container></section>
      <section className="report-section"><Container className="report-grid"><aside><span>01</span><h2>Research question</h2></aside><div className="report-body"><p className="report-lead">What does the fictional public evidence indicate about Northstar Thermal Systems’ readiness to increase assembly output for its modular industrial heat systems?</p><h3>Scope</h3><p>The demonstration considers fictional corporate material, planning information, vacancy notices, facility imagery and trade-fair content. It does not estimate precise output, cost, yield or customer demand.</p></div></Container></section>
      <section className="report-section report-tinted"><Container className="report-grid"><aside><span>02</span><h2>Executive summary</h2></aside><div className="report-body"><p className="report-lead">The evidence is consistent with a company preparing for increased operational throughput, but it does not confirm realised production capacity.</p><p>A permitted facility extension, visible construction and recruitment across production and supplier-quality roles form a coherent expansion signal. Product literature confirms a modular architecture that could support repeatable assembly. However, no fictional source establishes commissioning status, installed line rate, staffing completion or order coverage.</p><div className="finding-summary"><div><span>Overall assessment</span><strong>Expansion preparation is likely</strong></div><div><span>Confidence</span><ConfidenceBadge level="High confidence" /></div><div><span>Key limitation</span><strong>No verified output data</strong></div></div></div></Container></section>
      <section className="report-section"><Container><div className="report-section-heading"><span>03</span><h2>Evidence register</h2><p>Observations remain separate from the assessment they support.</p></div><SampleEvidenceTable /></Container></section>
      <section className="report-section report-tinted"><Container className="report-grid"><aside><span>04</span><h2>Key findings</h2></aside><div className="report-body"><div className="finding-list"><article><span>F1</span><div><h3>Physical expansion is supported by two source types.</h3><p>The fictional planning notice and dated external imagery are mutually consistent. Neither source verifies internal fit-out.</p></div><ConfidenceBadge level="High confidence" /></article><article><span>F2</span><div><h3>Hiring aligns with preparation for greater throughput.</h3><p>The mix of production engineering, supplier quality and shift supervision is more consistent with operational scaling than isolated replacement hiring.</p></div><ConfidenceBadge level="Moderate confidence" /></article><article><span>F3</span><div><h3>A next-generation product remains an early signal.</h3><p>The presentation reference lacks a validated specification, launch date or independent corroboration.</p></div><ConfidenceBadge level="Indicative" /></article></div></div></Container></section>
      <section className="report-section"><Container className="report-grid"><aside><span>05</span><h2>Limitations</h2></aside><div className="report-body"><ul className="editorial-list"><li>No source confirms installed equipment, line commissioning or achieved cycle time.</li><li>Vacancies may remain unfilled and do not prove that new shifts are operating.</li><li>External imagery cannot establish internal process capability or quality performance.</li><li>No reliable public evidence is available on order volume, supplier constraints or production yield.</li></ul></div></Container></section>
      <section className="report-section report-tinted"><Container className="report-grid"><aside><span>06</span><h2>Strategic implications</h2></aside><div className="report-body"><p>The evidence warrants treating Northstar as a competitor preparing to scale, but not yet as one with proven higher output. Commercial planning should distinguish between near-term signalling and verified delivery capability.</p><p>Supplier engagement and recruitment are the most useful public indicators to monitor next. A later commissioning reference, shift pattern change or product certification would materially raise confidence.</p><h3>Next questions</h3><ol className="numbered-questions"><li>Has the extension received an operational or occupancy approval?</li><li>Do equipment suppliers reference installation or commissioning?</li><li>Have production vacancies closed, repeated or shifted in seniority?</li><li>Does later product documentation show certification or serial availability?</li></ol></div></Container></section>
      <section className="closing-cta no-print"><Container className="closing-inner"><div><p className="eyebrow">Your decision, your scope</p><h2>Request a report built around a live question.</h2><p>The structure will be adapted to the evidence and decision—not copied mechanically from this demonstration.</p></div><ButtonLink href="/contact">Request a Report Like This</ButtonLink></Container></section>
    </article>
  );
}
