import type { Metadata } from "next";
import Link from "next/link";
import { ButtonLink } from "@/components/buttons";
import { Container } from "@/components/container";
import { PageHeader } from "@/components/page-header";
import { siteConfig } from "@/config/site";

export const metadata: Metadata = { title: "About", description: "How MelonCactus scopes industrial questions, verifies public evidence and reports uncertainty for business decisions.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <>
    <PageHeader eyebrow="About" title="Industrial questions deserve technical evidence." intro="MelonCactus helps industrial and technology decision-makers test defined questions using lawful public information and an inspectable evidence trail." breadcrumbs={[{ label: "About" }]} />
    <section className="section"><Container className="split-content"><div><p className="eyebrow">What we examine</p><h2>Specific claims, capabilities and exposures.</h2></div><div className="prose-block"><p>Suitable questions concern competitors, products, manufacturing and laboratory capabilities, technology choices, visible business relationships, market signals or an organisation’s own public-information footprint. The work is strongest when the buyer can name the decision and the uncertainty that could change it.</p><p>We do not assume that every question can be answered from public material. A request may need a narrower scope, more time, direct supplier diligence or a different type of specialist review.</p><p>{siteConfig.operatorStatement}</p></div></Container></section>
    <section className="section section-muted"><Container><div className="content-heading"><p className="eyebrow">How an engagement works</p><h2>A clear scope before research begins.</h2><p>The report option, delivery date and fee are confirmed in writing after the question and evidence needs have been reviewed.</p></div><div className="values-grid"><article><span>01</span><h3>Define the decision</h3><p>Agree the target, period, claims to test, exclusions and evidence threshold.</p></article><article><span>02</span><h3>Check provenance</h3><p>Record source origin, date and publication context; corroborate material findings where possible.</p></article><article><span>03</span><h3>Show uncertainty</h3><p>Keep observations separate from assessment and inference. Note contradictions and gaps.</p></article><article><span>04</span><h3>Deliver a usable report</h3><p>Present conclusions, confidence, source references, limitations and next questions.</p></article></div></Container></section>
    <section className="section"><Container className="split-content"><div><p className="eyebrow">Discretion and boundaries</p><h2>Useful detail without false certainty.</h2></div><div className="prose-block"><p>Enquiries and scopes are handled discreetly. Public client names or cases are not used without written permission. Research stays within lawfully accessible sources: no unauthorised access, impersonation, social engineering or unlawfully obtained material.</p><p>The buyer receives a report that can be challenged, not a polished assertion without a trail. Where evidence cannot responsibly establish capacity, intent or performance, the report says so and explains what would be needed to test the point.</p><p>Explore the <Link className="text-link" href="/methodology">research methodology</Link> or inspect the <Link className="text-link" href="/sample-report">fictional sample report</Link> to see the reporting format. The sample is a demonstration, not a client case.</p><ButtonLink href="/contact?call=true">Arrange a Confidential Call</ButtonLink></div></Container></section>
  </>;
}
