export const validPayload = {
  name: "Alex Example",
  email: "alex@business.test",
  company: "Acme Industries",
  role: "Director",
  decision: "Decide whether a supplier is suitable for a long-term programme.",
  target: "An industrial supplier and its production technology",
  report: "Focused Intelligence Assessment",
  deliveryPriority: "standard",
  geography: "Europe",
  budget: "€2,000–€4,000",
  context: "Please call first.",
  ndaRequest: "on",
  website: "",
};
