import type { Metadata } from "next";
import { Container } from "@/components/container";
import { PageHeader } from "@/components/page-header";
import { ServiceNextStep } from "@/components/service-next-step";
import { focusedServices } from "@/config/focused-services";

const service = focusedServices[1];
const path = `/services/${service.slug}`;

export const metadata: Metadata = {
  title: "Public-Source Manufacturing Capability Analysis",
  description: "Assess what public records, technical documents and published imagery indicate about industrial manufacturing or laboratory capability—not an on-site audit.",
  alternates: { canonical: path },
  openGraph: { type: "website", title: "Manufacturing Capability Analysis | MelonCactus", description: "A public-source assessment of equipment, process and expansion signals, with clear limits on proven capacity.", url: path },
};

export default function ManufacturingCapabilityAnalysisPage() {
  return <>
    <PageHeader eyebrow="Focused service / 02" title="What do public sources indicate about manufacturing capability?" intro="Public records, technical documents and published images can reveal useful signals about a facility or laboratory. They do not, by themselves, establish what a site can reliably produce today." breadcrumbs={[{ label: "Services", href: "/services" }, { label: service.title }]} />
    <section className="service-boundary-banner"><Container><strong>This is a public-source assessment, not an on-site factory audit.</strong> There is no physical inspection, equipment test or access to internal production records.</Container></section>
    <section className="section"><Container className="service-detail-grid"><div><p className="eyebrow">When this helps</p><h2>Understand the capability signal behind a claim.</h2></div><div className="service-prose"><p>A buyer may need to evaluate a prospective supplier, interpret a competitor’s expansion announcement or decide whether a laboratory capability is relevant to a technology programme. The assessment can frame what public material supports before committing to deeper diligence or an authorised site visit.</p><p>The question is carefully scoped: which process, location and period matter, and whether the decision requires evidence of equipment, a plausible process route or demonstrated output.</p></div></Container></section>
    <section className="section section-muted"><Container><div className="content-heading"><p className="eyebrow">Four different conclusions</p><h2>Presence, possibility, preparation and production are not synonyms.</h2></div><div className="service-signal-grid"><article><span>01</span><h3>Installed equipment</h3><p>A dated, attributable source may show equipment at a location. It may not establish whether the asset is commissioned or in routine use.</p></article><article><span>02</span><h3>Possible process</h3><p>Equipment type, specifications and surrounding infrastructure may be consistent with a process. Hidden configuration and operating conditions remain unknown.</p></article><article><span>03</span><h3>Expansion signal</h3><p>Permits, building changes, supplier announcements and hiring may indicate preparation. They do not prove that additional capacity is online.</p></article><article><span>04</span><h3>Proven capacity</h3><p>Actual throughput, yield and repeatability require direct, credible operating evidence; public sources often do not provide it.</p></article></div></Container></section>
    <section className="section"><Container className="service-detail-grid"><div><p className="eyebrow">Evidence and method</p><h2>Build a dated, cross-checked capability picture.</h2></div><div className="service-prose"><p>Potential sources include public planning and permit records, certifications, equipment manuals, product specifications, patents, supplier references, vacancies and lawfully published photographs or video. Image provenance, apparent date, viewpoint and publication purpose are checked before interpreting a visible feature.</p><p>We compare source types and changes over time, test alternative explanations and identify whether each finding is an observation, an assessment or an inference. A photograph of a machine, for example, may corroborate an installation claim; it does not validate cycle time or product quality.</p><h3>The deliverable</h3><p>A capability assessment sets out the defined site or process question, an evidence timeline, observed assets and process indicators, confidence by finding, competing explanations and a list of material unknowns. It identifies the public evidence that could next improve confidence and the questions that would require direct supplier diligence.</p></div></Container></section>
    <section className="section service-limits"><Container className="service-detail-grid"><div><p className="eyebrow">Limits</p><h2>No inferred output without operating evidence.</h2></div><div className="service-prose"><p>Published imagery cannot verify internal tolerances, commissioning status, staffing, line rate, yield, quality systems in operation or sustained production capacity. Absence of a visible asset is not proof that it is absent from the site. The assessment does not replace an on-site audit, engineering inspection or contractual supplier qualification.</p></div></Container></section>
    <ServiceNextStep service={service} scopeNote="A Technical Deep Dive is an indicative fit when the question spans records, technical documents and imagery. A narrower first scan or broader investigation can be scoped instead." />
  </>;
}
