import type { Metadata } from "next";
import { Container } from "@/components/container";
import { PageHeader } from "@/components/page-header";
import { siteConfig } from "@/config/site";

export const metadata: Metadata = { title: "Privacy", description: "Privacy information for the Lemon Cactus website.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() { return <><PageHeader eyebrow="Information" title="Privacy statement" intro="A plain account of what this website currently does—and does not do—with personal information." breadcrumbs={[{ label: "Privacy" }]} /><section className="section"><Container className="legal-copy"><p className="legal-updated">Last updated: 22 September 2026</p><h2>Current website behaviour</h2><p>This first version does not use advertising trackers, behavioural profiling or non-essential cookies. No cookie banner is shown because the site does not currently set cookies that require consent.</p><h2>Enquiry form</h2><p>The enquiry form currently performs validation in your browser but is not connected to a transmission or storage provider. Information entered is not sent to Lemon Cactus. This will be updated before the form is activated.</p><h2>Information to avoid</h2><p>Do not provide passwords, unlawfully obtained material, special-category personal data or more personal information than is necessary to explain a research question.</p><h2>Future providers</h2><p>If a form, email or privacy-respecting analytics provider is connected later, this statement will be updated to explain the purpose, lawful basis, retention period and relevant processor before collection begins.</p><h2>Contact and responsible entity</h2><p>The business email, legal entity and postal address are awaiting verification. The current configuration placeholders are {siteConfig.businessEmail}, {siteConfig.legalName}, and {siteConfig.postalAddress}. These must be replaced before launch.</p></Container></section></>; }

