import type { Metadata } from "next";
import { LegalPageShell } from "@/components/legal-page-shell";
import { siteConfig } from "@/config/site";
import { languageAlternates } from "@/lib/i18n";

export const metadata: Metadata = {
  title: "Privacy statement", description: "How MelonCactus handles enquiries, website measurement and personal information in public-source research.",
  alternates: languageAlternates("/privacy", "en"),
};

export default function PrivacyPage() {
  return (
    <LegalPageShell title="Privacy statement" intro="How we handle personal information when you visit the site, make an enquiry or work with us." updated="3 October 2026">
      <h2>Who is responsible?</h2>
      <p>{siteConfig.legalName}, a Dutch sole proprietorship operating MelonCactus, is the controller for the website, business contacts and its own assignment administration (Dutch Chamber of Commerce number {siteConfig.registrationNumber}; VAT ID {siteConfig.vatId}). We determine our role for commissioned research case by case. Our business address is {siteConfig.postalAddress}. For questions or privacy requests, email <a href={`mailto:${siteConfig.businessEmail}`}>{siteConfig.businessEmail}</a> or call <a href={siteConfig.businessPhoneHref}>{siteConfig.businessPhoneDisplay}</a>.</p>
      <h2>Enquiries and business correspondence</h2>
      <p>The form asks for your name, work email, company and role, the decision and research subject, and requested timing. The assessment level, geography, budget, additional context and NDA discussion request are optional. We use these details, and any subsequent business correspondence, to assess and answer your question, prepare a possible proposal and communicate with you. An enquiry is not an accepted assignment; requesting an NDA does not create one. Please do not send passwords, credentials, unlawfully obtained material, confidential documents or unnecessary sensitive personal data in the initial form.</p>
      <p>If you request or enter into a contract in your own name, we process the information needed to take steps at your request before the contract or to perform it. For employees and other contacts acting for a company, we rely on our legitimate interest in handling business enquiries and correspondence. We limit this to relevant information, do not use the form for marketing subscriptions and respect your right to object.</p>
      <h2>Assignments and public-source research</h2>
      <p>For an agreed assignment, we use contact, project and invoice details to perform and administer it. Contract performance may be the basis for an individual client; for a company’s representatives we rely on our legitimate interest in carrying out the business assignment. A legal obligation also applies to necessary financial records. Research may include personal information from lawfully accessible public sources. Publicly available information remains personal information. For each assignment we determine our role and assess necessity, proportionality, professional relevance, source reliability and information duties for indirectly obtained information. Depending on that assessment, our legitimate interest or another applicable basis may apply. We do not assume a general exemption from the duty to inform people.</p>
      <h2>Hosting, security and website measurement</h2>
      <p>Vercel hosts the website and may process technical request and security information to serve and protect it. We rely on our legitimate interest in providing an available and secure website. With Vercel Web Analytics we measure only page views on known public English and Dutch pages so we can improve the site&apos;s navigation and content. Our site code removes query strings and fragments from the page URL it passes as an Analytics event and does not send form field values as Analytics events. Vercel says the statistical data may include the time, page path, referring website, approximate location, and browser and device information. When receiving a request, Vercel may also process connection data such as an IP address; Vercel describes a short-lived visitor hash created from the incoming request, without third-party Analytics cookies. We do not use this measurement for advertising or individual visitor profiles. For this limited measurement we rely on our legitimate interest in understanding and improving use of the website. You may object by emailing <a href={`mailto:${siteConfig.businessEmail}`}>{siteConfig.businessEmail}</a>. A visitor session expiring after 24 hours does not mean that all Analytics or hosting data is deleted then.</p>
      <h2>Recipients and international processing</h2>
      <p>Resend delivers form enquiries to our business mailbox, provided by OVHcloud through Zimbra; Outlook is the email client. Vercel provides hosting and website measurement. Research working files and reports are currently stored locally on our computer. We share information with service providers as needed for these purposes and, for an assignment, with the client or other agreed recipients. Some processing takes place outside the European Economic Area, including Resend&apos;s storage of email content and delivery logs in the United States. We do not claim EEA-only storage. <a href="https://resend.com/legal/dpa">Resend&apos;s published data processing addendum</a> describes when it becomes binding and incorporates EU standard contractual clauses for relevant transfers; Resend also describes its participation in the EU–US Data Privacy Framework. The <a href="https://vercel.com/legal/dpa">Vercel Pro data processing addendum</a> incorporates EU standard contractual clauses for transfers where they are required. These are provider-specific safeguards, not a guarantee that all processing stays in Europe. You may request more information about the safeguards relevant to your data by contacting us at <a href={`mailto:${siteConfig.businessEmail}`}>{siteConfig.businessEmail}</a>.</p>
      <h2>How long do we keep information?</h2>
      <p>Enquiries that do not become assignments, including related correspondence, are deleted from our active business mailbox and working files no later than twelve months after the last substantive contact, or sooner when follow-up is no longer needed. Research working files for a completed assignment are deleted from our active working files no later than 24 months after final delivery, or sooner when no longer needed. We retain final reports only while needed for corrections or proportionate contractual claims; they are reviewed separately from working files. Scope confirmations and other records needed for financial administration are kept for the applicable statutory period, generally seven years in the Netherlands. A concrete legal claim may justify longer retention of only the relevant records, assessed separately. These active-file periods do not guarantee deletion of provider-held copies or security records. Different deletion processes, backup cycles and legal exceptions may apply there. Resend describes a routine 30-day period for email content and logs on its Free, Pro and Scale plans; its separate period after account termination is not the retention period for our active mailbox. Vercel says its Analytics visitor session is discarded after 24 hours; that is not a general deletion period for all Analytics or hosting data.</p>
      <h2>Your rights</h2>
      <p>You may request access, correction, deletion or restriction of processing, and object to processing based on legitimate interests. Data portability applies where its legal conditions are met. If we ever rely on consent for a particular processing operation, you may withdraw it without affecting earlier lawful processing. Contact us by email; we may ask only for information needed to verify your identity. You can also complain to the Dutch Data Protection Authority (Autoriteit Persoonsgegevens).</p>
      <h2>Changes</h2>
      <p>We update this notice when our processing materially changes and show the revision date above. Material changes should be communicated through an appropriate channel where required.</p>
    </LegalPageShell>
  );
}
